name: Web Searcher Evaluation Pipeline

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'agent_hub/web_searcher/**'

jobs:
  evaluate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirement.txt

    - name: Run basic tests
      run: |
        python -m pytest tests/agent_hub/web_searcher/

    - name: Run evaluation pipeline
      run: |
        python evaluation/pipelines/web_searcher_pipeline.py

    - name: Upload evaluation results
      uses: actions/upload-artifact@v3
      with:
        name: evaluation-results
        path: |
          evaluation/results/**
          evaluation/*.log